apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersapi
  labels:
    app: ordersapi
spec:
  selector:
    matchLabels:
      app: ordersapi
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ordersapi
    spec:
      containers:
      - name: ordersapi
        image: iamnilanjan3/ecom-users-api:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        env:
        - name: MONGODB_URL
          value: mongodb://root:root@mongodb-0.mongodb-headless:27017/
        - name: ORDERS_API_URL
          value: http://ordersapi:5151
        ports:
        - containerPort: 5151
          protocol: TCP
      restartPolicy: Always
      # securityContext:
      #   runAsUser: 0
      # terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: ordersapi
  labels:
    app: ordersapi
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5151
      targetPort: 5151
      protocol: TCP
  selector:
    app: ordersapi